#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsmansGuide
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CurtData")]
	public partial class LINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertConnector(Connector instance);
    partial void UpdateConnector(Connector instance);
    partial void DeleteConnector(Connector instance);
    partial void InsertVehicle(Vehicle instance);
    partial void UpdateVehicle(Vehicle instance);
    partial void DeleteVehicle(Vehicle instance);
    partial void InsertConnector1(Connector1 instance);
    partial void UpdateConnector1(Connector1 instance);
    partial void DeleteConnector1(Connector1 instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    #endregion
		
		public LINQDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CurtDataConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Connector> Connectors
		{
			get
			{
				return this.GetTable<Connector>();
			}
		}
		
		public System.Data.Linq.Table<Vehicle> Vehicles
		{
			get
			{
				return this.GetTable<Vehicle>();
			}
		}
		
		public System.Data.Linq.Table<SGIDCross> SGIDCrosses
		{
			get
			{
				return this.GetTable<SGIDCross>();
			}
		}
		
		public System.Data.Linq.Table<CatPart> CatParts
		{
			get
			{
				return this.GetTable<CatPart>();
			}
		}
		
		public System.Data.Linq.Table<Category> Categories
		{
			get
			{
				return this.GetTable<Category>();
			}
		}
		
		public System.Data.Linq.Table<Connector1> Connector1s
		{
			get
			{
				return this.GetTable<Connector1>();
			}
		}
		
		public System.Data.Linq.Table<CPart> CParts
		{
			get
			{
				return this.GetTable<CPart>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Connector")]
	public partial class Connector : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iConnectorID;
		
		private string _vchConnectorCode;
		
		private string _vchConnectorUPC;
		
		private System.Nullable<decimal> _mConnectorList;
		
		private System.Nullable<decimal> _mConnectorMap;
		
		private System.Nullable<double> _fConnectorShippingWeight;
		
		private string _vchConnectorInstallTime;
		
		private string _txtConnectorNotes;
		
		private System.Nullable<int> _iVehicleID;
		
		private System.Nullable<int> _iConnectorClassID;
		
		private EntityRef<Vehicle> _Vehicle;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniConnectorIDChanging(int value);
    partial void OniConnectorIDChanged();
    partial void OnvchConnectorCodeChanging(string value);
    partial void OnvchConnectorCodeChanged();
    partial void OnvchConnectorUPCChanging(string value);
    partial void OnvchConnectorUPCChanged();
    partial void OnmConnectorListChanging(System.Nullable<decimal> value);
    partial void OnmConnectorListChanged();
    partial void OnmConnectorMapChanging(System.Nullable<decimal> value);
    partial void OnmConnectorMapChanged();
    partial void OnfConnectorShippingWeightChanging(System.Nullable<double> value);
    partial void OnfConnectorShippingWeightChanged();
    partial void OnvchConnectorInstallTimeChanging(string value);
    partial void OnvchConnectorInstallTimeChanged();
    partial void OntxtConnectorNotesChanging(string value);
    partial void OntxtConnectorNotesChanged();
    partial void OniVehicleIDChanging(System.Nullable<int> value);
    partial void OniVehicleIDChanged();
    partial void OniConnectorClassIDChanging(System.Nullable<int> value);
    partial void OniConnectorClassIDChanged();
    #endregion
		
		public Connector()
		{
			this._Vehicle = default(EntityRef<Vehicle>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iConnectorID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iConnectorID
		{
			get
			{
				return this._iConnectorID;
			}
			set
			{
				if ((this._iConnectorID != value))
				{
					this.OniConnectorIDChanging(value);
					this.SendPropertyChanging();
					this._iConnectorID = value;
					this.SendPropertyChanged("iConnectorID");
					this.OniConnectorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchConnectorCode", DbType="NVarChar(100)")]
		public string vchConnectorCode
		{
			get
			{
				return this._vchConnectorCode;
			}
			set
			{
				if ((this._vchConnectorCode != value))
				{
					this.OnvchConnectorCodeChanging(value);
					this.SendPropertyChanging();
					this._vchConnectorCode = value;
					this.SendPropertyChanged("vchConnectorCode");
					this.OnvchConnectorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchConnectorUPC", DbType="NVarChar(50)")]
		public string vchConnectorUPC
		{
			get
			{
				return this._vchConnectorUPC;
			}
			set
			{
				if ((this._vchConnectorUPC != value))
				{
					this.OnvchConnectorUPCChanging(value);
					this.SendPropertyChanging();
					this._vchConnectorUPC = value;
					this.SendPropertyChanged("vchConnectorUPC");
					this.OnvchConnectorUPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mConnectorList", DbType="Money")]
		public System.Nullable<decimal> mConnectorList
		{
			get
			{
				return this._mConnectorList;
			}
			set
			{
				if ((this._mConnectorList != value))
				{
					this.OnmConnectorListChanging(value);
					this.SendPropertyChanging();
					this._mConnectorList = value;
					this.SendPropertyChanged("mConnectorList");
					this.OnmConnectorListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mConnectorMap", DbType="Money")]
		public System.Nullable<decimal> mConnectorMap
		{
			get
			{
				return this._mConnectorMap;
			}
			set
			{
				if ((this._mConnectorMap != value))
				{
					this.OnmConnectorMapChanging(value);
					this.SendPropertyChanging();
					this._mConnectorMap = value;
					this.SendPropertyChanged("mConnectorMap");
					this.OnmConnectorMapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fConnectorShippingWeight", DbType="Float")]
		public System.Nullable<double> fConnectorShippingWeight
		{
			get
			{
				return this._fConnectorShippingWeight;
			}
			set
			{
				if ((this._fConnectorShippingWeight != value))
				{
					this.OnfConnectorShippingWeightChanging(value);
					this.SendPropertyChanging();
					this._fConnectorShippingWeight = value;
					this.SendPropertyChanged("fConnectorShippingWeight");
					this.OnfConnectorShippingWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchConnectorInstallTime", DbType="NVarChar(100)")]
		public string vchConnectorInstallTime
		{
			get
			{
				return this._vchConnectorInstallTime;
			}
			set
			{
				if ((this._vchConnectorInstallTime != value))
				{
					this.OnvchConnectorInstallTimeChanging(value);
					this.SendPropertyChanging();
					this._vchConnectorInstallTime = value;
					this.SendPropertyChanged("vchConnectorInstallTime");
					this.OnvchConnectorInstallTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtConnectorNotes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string txtConnectorNotes
		{
			get
			{
				return this._txtConnectorNotes;
			}
			set
			{
				if ((this._txtConnectorNotes != value))
				{
					this.OntxtConnectorNotesChanging(value);
					this.SendPropertyChanging();
					this._txtConnectorNotes = value;
					this.SendPropertyChanged("txtConnectorNotes");
					this.OntxtConnectorNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iVehicleID", DbType="Int")]
		public System.Nullable<int> iVehicleID
		{
			get
			{
				return this._iVehicleID;
			}
			set
			{
				if ((this._iVehicleID != value))
				{
					if (this._Vehicle.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniVehicleIDChanging(value);
					this.SendPropertyChanging();
					this._iVehicleID = value;
					this.SendPropertyChanged("iVehicleID");
					this.OniVehicleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iConnectorClassID", DbType="Int")]
		public System.Nullable<int> iConnectorClassID
		{
			get
			{
				return this._iConnectorClassID;
			}
			set
			{
				if ((this._iConnectorClassID != value))
				{
					this.OniConnectorClassIDChanging(value);
					this.SendPropertyChanging();
					this._iConnectorClassID = value;
					this.SendPropertyChanged("iConnectorClassID");
					this.OniConnectorClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vehicle_Connector", Storage="_Vehicle", ThisKey="iVehicleID", OtherKey="iVehicleID", IsForeignKey=true)]
		public Vehicle Vehicle
		{
			get
			{
				return this._Vehicle.Entity;
			}
			set
			{
				Vehicle previousValue = this._Vehicle.Entity;
				if (((previousValue != value) 
							|| (this._Vehicle.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vehicle.Entity = null;
						previousValue.Connectors.Remove(this);
					}
					this._Vehicle.Entity = value;
					if ((value != null))
					{
						value.Connectors.Add(this);
						this._iVehicleID = value.iVehicleID;
					}
					else
					{
						this._iVehicleID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Vehicle");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vehicle")]
	public partial class Vehicle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iVehicleID;
		
		private string _vchYear;
		
		private string _vchMake;
		
		private string _vchModel;
		
		private string _vchStyle;
		
		private string _vchInstallTime;
		
		private EntitySet<Connector> _Connectors;
		
		private EntitySet<Connector1> _Connector1s;
		
		private EntitySet<Product> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniVehicleIDChanging(int value);
    partial void OniVehicleIDChanged();
    partial void OnvchYearChanging(string value);
    partial void OnvchYearChanged();
    partial void OnvchMakeChanging(string value);
    partial void OnvchMakeChanged();
    partial void OnvchModelChanging(string value);
    partial void OnvchModelChanged();
    partial void OnvchStyleChanging(string value);
    partial void OnvchStyleChanged();
    partial void OnvchInstallTimeChanging(string value);
    partial void OnvchInstallTimeChanged();
    #endregion
		
		public Vehicle()
		{
			this._Connectors = new EntitySet<Connector>(new Action<Connector>(this.attach_Connectors), new Action<Connector>(this.detach_Connectors));
			this._Connector1s = new EntitySet<Connector1>(new Action<Connector1>(this.attach_Connector1s), new Action<Connector1>(this.detach_Connector1s));
			this._Products = new EntitySet<Product>(new Action<Product>(this.attach_Products), new Action<Product>(this.detach_Products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iVehicleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iVehicleID
		{
			get
			{
				return this._iVehicleID;
			}
			set
			{
				if ((this._iVehicleID != value))
				{
					this.OniVehicleIDChanging(value);
					this.SendPropertyChanging();
					this._iVehicleID = value;
					this.SendPropertyChanged("iVehicleID");
					this.OniVehicleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchYear", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string vchYear
		{
			get
			{
				return this._vchYear;
			}
			set
			{
				if ((this._vchYear != value))
				{
					this.OnvchYearChanging(value);
					this.SendPropertyChanging();
					this._vchYear = value;
					this.SendPropertyChanged("vchYear");
					this.OnvchYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchMake", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string vchMake
		{
			get
			{
				return this._vchMake;
			}
			set
			{
				if ((this._vchMake != value))
				{
					this.OnvchMakeChanging(value);
					this.SendPropertyChanging();
					this._vchMake = value;
					this.SendPropertyChanged("vchMake");
					this.OnvchMakeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchModel", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string vchModel
		{
			get
			{
				return this._vchModel;
			}
			set
			{
				if ((this._vchModel != value))
				{
					this.OnvchModelChanging(value);
					this.SendPropertyChanging();
					this._vchModel = value;
					this.SendPropertyChanged("vchModel");
					this.OnvchModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchStyle", DbType="NVarChar(100)")]
		public string vchStyle
		{
			get
			{
				return this._vchStyle;
			}
			set
			{
				if ((this._vchStyle != value))
				{
					this.OnvchStyleChanging(value);
					this.SendPropertyChanging();
					this._vchStyle = value;
					this.SendPropertyChanged("vchStyle");
					this.OnvchStyleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchInstallTime", DbType="NVarChar(100)")]
		public string vchInstallTime
		{
			get
			{
				return this._vchInstallTime;
			}
			set
			{
				if ((this._vchInstallTime != value))
				{
					this.OnvchInstallTimeChanging(value);
					this.SendPropertyChanging();
					this._vchInstallTime = value;
					this.SendPropertyChanged("vchInstallTime");
					this.OnvchInstallTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vehicle_Connector", Storage="_Connectors", ThisKey="iVehicleID", OtherKey="iVehicleID")]
		public EntitySet<Connector> Connectors
		{
			get
			{
				return this._Connectors;
			}
			set
			{
				this._Connectors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vehicle_Connector1", Storage="_Connector1s", ThisKey="iVehicleID", OtherKey="iVehicleID")]
		public EntitySet<Connector1> Connector1s
		{
			get
			{
				return this._Connector1s;
			}
			set
			{
				this._Connector1s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vehicle_Product", Storage="_Products", ThisKey="iVehicleID", OtherKey="iVehicleID")]
		public EntitySet<Product> Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Connectors(Connector entity)
		{
			this.SendPropertyChanging();
			entity.Vehicle = this;
		}
		
		private void detach_Connectors(Connector entity)
		{
			this.SendPropertyChanging();
			entity.Vehicle = null;
		}
		
		private void attach_Connector1s(Connector1 entity)
		{
			this.SendPropertyChanging();
			entity.Vehicle = this;
		}
		
		private void detach_Connector1s(Connector1 entity)
		{
			this.SendPropertyChanging();
			entity.Vehicle = null;
		}
		
		private void attach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Vehicle = this;
		}
		
		private void detach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Vehicle = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGIDCross")]
	public partial class SGIDCross
	{
		
		private string _SGID;
		
		private string _CURTID;
		
		private decimal _SGRetail;
		
		private decimal _SGMemPrice;
		
		public SGIDCross()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGID", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string SGID
		{
			get
			{
				return this._SGID;
			}
			set
			{
				if ((this._SGID != value))
				{
					this._SGID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURTID", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string CURTID
		{
			get
			{
				return this._CURTID;
			}
			set
			{
				if ((this._CURTID != value))
				{
					this._CURTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGRetail", DbType="Money NOT NULL")]
		public decimal SGRetail
		{
			get
			{
				return this._SGRetail;
			}
			set
			{
				if ((this._SGRetail != value))
				{
					this._SGRetail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGMemPrice", DbType="Money NOT NULL")]
		public decimal SGMemPrice
		{
			get
			{
				return this._SGMemPrice;
			}
			set
			{
				if ((this._SGMemPrice != value))
				{
					this._SGMemPrice = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CatParts")]
	public partial class CatPart
	{
		
		private string _vchProductCode;
		
		private System.Nullable<int> _CatID;
		
		private System.Nullable<int> _ParentID;
		
		public CatPart()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductCode", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string vchProductCode
		{
			get
			{
				return this._vchProductCode;
			}
			set
			{
				if ((this._vchProductCode != value))
				{
					this._vchProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatID", DbType="Int")]
		public System.Nullable<int> CatID
		{
			get
			{
				return this._CatID;
			}
			set
			{
				if ((this._CatID != value))
				{
					this._CatID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Category")]
	public partial class Category
	{
		
		private System.Nullable<int> _CatID;
		
		private System.Nullable<int> _ParentID;
		
		private string _CatTitle;
		
		private System.Nullable<int> _CatTypeID;
		
		private string _shortDesc;
		
		private string _longDesc;
		
		private string _CatImage;
		
		public Category()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatID", DbType="Int")]
		public System.Nullable<int> CatID
		{
			get
			{
				return this._CatID;
			}
			set
			{
				if ((this._CatID != value))
				{
					this._CatID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatTitle", DbType="NChar(42)")]
		public string CatTitle
		{
			get
			{
				return this._CatTitle;
			}
			set
			{
				if ((this._CatTitle != value))
				{
					this._CatTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatTypeID", DbType="Int")]
		public System.Nullable<int> CatTypeID
		{
			get
			{
				return this._CatTypeID;
			}
			set
			{
				if ((this._CatTypeID != value))
				{
					this._CatTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortDesc", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string shortDesc
		{
			get
			{
				return this._shortDesc;
			}
			set
			{
				if ((this._shortDesc != value))
				{
					this._shortDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longDesc", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string longDesc
		{
			get
			{
				return this._longDesc;
			}
			set
			{
				if ((this._longDesc != value))
				{
					this._longDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatImage", DbType="NVarChar(150)")]
		public string CatImage
		{
			get
			{
				return this._CatImage;
			}
			set
			{
				if ((this._CatImage != value))
				{
					this._CatImage = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Connector")]
	public partial class Connector1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iConnectorID;
		
		private string _vchConnectorCode;
		
		private string _vchConnectorUPC;
		
		private System.Nullable<decimal> _mConnectorList;
		
		private System.Nullable<decimal> _mConnectorMap;
		
		private System.Nullable<double> _fConnectorShippingWeight;
		
		private string _vchConnectorInstallTime;
		
		private string _txtConnectorNotes;
		
		private System.Nullable<int> _iVehicleID;
		
		private System.Nullable<int> _iConnectorClassID;
		
		private EntityRef<Vehicle> _Vehicle;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniConnectorIDChanging(int value);
    partial void OniConnectorIDChanged();
    partial void OnvchConnectorCodeChanging(string value);
    partial void OnvchConnectorCodeChanged();
    partial void OnvchConnectorUPCChanging(string value);
    partial void OnvchConnectorUPCChanged();
    partial void OnmConnectorListChanging(System.Nullable<decimal> value);
    partial void OnmConnectorListChanged();
    partial void OnmConnectorMapChanging(System.Nullable<decimal> value);
    partial void OnmConnectorMapChanged();
    partial void OnfConnectorShippingWeightChanging(System.Nullable<double> value);
    partial void OnfConnectorShippingWeightChanged();
    partial void OnvchConnectorInstallTimeChanging(string value);
    partial void OnvchConnectorInstallTimeChanged();
    partial void OntxtConnectorNotesChanging(string value);
    partial void OntxtConnectorNotesChanged();
    partial void OniVehicleIDChanging(System.Nullable<int> value);
    partial void OniVehicleIDChanged();
    partial void OniConnectorClassIDChanging(System.Nullable<int> value);
    partial void OniConnectorClassIDChanged();
    #endregion
		
		public Connector1()
		{
			this._Vehicle = default(EntityRef<Vehicle>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iConnectorID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iConnectorID
		{
			get
			{
				return this._iConnectorID;
			}
			set
			{
				if ((this._iConnectorID != value))
				{
					this.OniConnectorIDChanging(value);
					this.SendPropertyChanging();
					this._iConnectorID = value;
					this.SendPropertyChanged("iConnectorID");
					this.OniConnectorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchConnectorCode", DbType="NVarChar(100)")]
		public string vchConnectorCode
		{
			get
			{
				return this._vchConnectorCode;
			}
			set
			{
				if ((this._vchConnectorCode != value))
				{
					this.OnvchConnectorCodeChanging(value);
					this.SendPropertyChanging();
					this._vchConnectorCode = value;
					this.SendPropertyChanged("vchConnectorCode");
					this.OnvchConnectorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchConnectorUPC", DbType="NVarChar(50)")]
		public string vchConnectorUPC
		{
			get
			{
				return this._vchConnectorUPC;
			}
			set
			{
				if ((this._vchConnectorUPC != value))
				{
					this.OnvchConnectorUPCChanging(value);
					this.SendPropertyChanging();
					this._vchConnectorUPC = value;
					this.SendPropertyChanged("vchConnectorUPC");
					this.OnvchConnectorUPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mConnectorList", DbType="Money")]
		public System.Nullable<decimal> mConnectorList
		{
			get
			{
				return this._mConnectorList;
			}
			set
			{
				if ((this._mConnectorList != value))
				{
					this.OnmConnectorListChanging(value);
					this.SendPropertyChanging();
					this._mConnectorList = value;
					this.SendPropertyChanged("mConnectorList");
					this.OnmConnectorListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mConnectorMap", DbType="Money")]
		public System.Nullable<decimal> mConnectorMap
		{
			get
			{
				return this._mConnectorMap;
			}
			set
			{
				if ((this._mConnectorMap != value))
				{
					this.OnmConnectorMapChanging(value);
					this.SendPropertyChanging();
					this._mConnectorMap = value;
					this.SendPropertyChanged("mConnectorMap");
					this.OnmConnectorMapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fConnectorShippingWeight", DbType="Float")]
		public System.Nullable<double> fConnectorShippingWeight
		{
			get
			{
				return this._fConnectorShippingWeight;
			}
			set
			{
				if ((this._fConnectorShippingWeight != value))
				{
					this.OnfConnectorShippingWeightChanging(value);
					this.SendPropertyChanging();
					this._fConnectorShippingWeight = value;
					this.SendPropertyChanged("fConnectorShippingWeight");
					this.OnfConnectorShippingWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchConnectorInstallTime", DbType="NVarChar(100)")]
		public string vchConnectorInstallTime
		{
			get
			{
				return this._vchConnectorInstallTime;
			}
			set
			{
				if ((this._vchConnectorInstallTime != value))
				{
					this.OnvchConnectorInstallTimeChanging(value);
					this.SendPropertyChanging();
					this._vchConnectorInstallTime = value;
					this.SendPropertyChanged("vchConnectorInstallTime");
					this.OnvchConnectorInstallTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtConnectorNotes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string txtConnectorNotes
		{
			get
			{
				return this._txtConnectorNotes;
			}
			set
			{
				if ((this._txtConnectorNotes != value))
				{
					this.OntxtConnectorNotesChanging(value);
					this.SendPropertyChanging();
					this._txtConnectorNotes = value;
					this.SendPropertyChanged("txtConnectorNotes");
					this.OntxtConnectorNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iVehicleID", DbType="Int")]
		public System.Nullable<int> iVehicleID
		{
			get
			{
				return this._iVehicleID;
			}
			set
			{
				if ((this._iVehicleID != value))
				{
					if (this._Vehicle.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniVehicleIDChanging(value);
					this.SendPropertyChanging();
					this._iVehicleID = value;
					this.SendPropertyChanged("iVehicleID");
					this.OniVehicleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iConnectorClassID", DbType="Int")]
		public System.Nullable<int> iConnectorClassID
		{
			get
			{
				return this._iConnectorClassID;
			}
			set
			{
				if ((this._iConnectorClassID != value))
				{
					this.OniConnectorClassIDChanging(value);
					this.SendPropertyChanging();
					this._iConnectorClassID = value;
					this.SendPropertyChanged("iConnectorClassID");
					this.OniConnectorClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vehicle_Connector1", Storage="_Vehicle", ThisKey="iVehicleID", OtherKey="iVehicleID", IsForeignKey=true)]
		public Vehicle Vehicle
		{
			get
			{
				return this._Vehicle.Entity;
			}
			set
			{
				Vehicle previousValue = this._Vehicle.Entity;
				if (((previousValue != value) 
							|| (this._Vehicle.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vehicle.Entity = null;
						previousValue.Connector1s.Remove(this);
					}
					this._Vehicle.Entity = value;
					if ((value != null))
					{
						value.Connector1s.Add(this);
						this._iVehicleID = value.iVehicleID;
					}
					else
					{
						this._iVehicleID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Vehicle");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CParts")]
	public partial class CPart
	{
		
		private string _vchProductCode;
		
		private string _vchPartUPC;
		
		private string _vchSDesc;
		
		private string _vchCategDesc;
		
		private string _SGID;
		
		private decimal _SGRetail;
		
		private string _vchParams;
		
		public CPart()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductCode", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string vchProductCode
		{
			get
			{
				return this._vchProductCode;
			}
			set
			{
				if ((this._vchProductCode != value))
				{
					this._vchProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchPartUPC", DbType="NVarChar(25)")]
		public string vchPartUPC
		{
			get
			{
				return this._vchPartUPC;
			}
			set
			{
				if ((this._vchPartUPC != value))
				{
					this._vchPartUPC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchSDesc", DbType="NVarChar(75)")]
		public string vchSDesc
		{
			get
			{
				return this._vchSDesc;
			}
			set
			{
				if ((this._vchSDesc != value))
				{
					this._vchSDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCategDesc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string vchCategDesc
		{
			get
			{
				return this._vchCategDesc;
			}
			set
			{
				if ((this._vchCategDesc != value))
				{
					this._vchCategDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGID", DbType="NChar(16) NOT NULL", CanBeNull=false)]
		public string SGID
		{
			get
			{
				return this._SGID;
			}
			set
			{
				if ((this._SGID != value))
				{
					this._SGID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGRetail", DbType="Money NOT NULL")]
		public decimal SGRetail
		{
			get
			{
				return this._SGRetail;
			}
			set
			{
				if ((this._SGRetail != value))
				{
					this._SGRetail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchParams", DbType="NVarChar(200)")]
		public string vchParams
		{
			get
			{
				return this._vchParams;
			}
			set
			{
				if ((this._vchParams != value))
				{
					this._vchParams = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iProductID;
		
		private string _vchProductCode;
		
		private string _vchPriceCode;
		
		private string _vchHitchUPC;
		
		private System.Nullable<decimal> _mHitchList;
		
		private System.Nullable<decimal> _mHitchMap;
		
		private System.Nullable<double> _fShippingWeight;
		
		private string _vchWC;
		
		private string _vchWD;
		
		private string _vchCapacity;
		
		private string _txtNote1;
		
		private string _txtNote2;
		
		private string _txtNote3;
		
		private string _txtNote4;
		
		private string _vchDrilling;
		
		private string _vchUPCList;
		
		private string _vchExposed;
		
		private string _vchShortDesc;
		
		private System.Nullable<int> _iVehicleID;
		
		private System.Nullable<int> _iProductClassID;
		
		private System.Nullable<System.DateTime> _dtDateMod;
		
		private string _txtBullet1;
		
		private string _txtBullet2;
		
		private string _txtBullet3;
		
		private string _txtBullet4;
		
		private string _txtBullet5;
		
		private string _vchLongDesc;
		
		private System.Nullable<int> _iUniqueIdentifier;
		
		private System.Nullable<System.DateTime> _dtDateLastTouched;
		
		private string _txtNote6;
		
		private System.Nullable<int> _InstallTime;
		
		private string _SGID;
		
		private string _CURTID;
		
		private System.Nullable<decimal> _SGRetail;
		
		private System.Nullable<decimal> _SGMemPrice;
		
		private string _InstallSheet;
		
		private System.Nullable<decimal> _mHitchJobber;
		
		private EntityRef<Vehicle> _Vehicle;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniProductIDChanging(int value);
    partial void OniProductIDChanged();
    partial void OnvchProductCodeChanging(string value);
    partial void OnvchProductCodeChanged();
    partial void OnvchPriceCodeChanging(string value);
    partial void OnvchPriceCodeChanged();
    partial void OnvchHitchUPCChanging(string value);
    partial void OnvchHitchUPCChanged();
    partial void OnmHitchListChanging(System.Nullable<decimal> value);
    partial void OnmHitchListChanged();
    partial void OnmHitchMapChanging(System.Nullable<decimal> value);
    partial void OnmHitchMapChanged();
    partial void OnfShippingWeightChanging(System.Nullable<double> value);
    partial void OnfShippingWeightChanged();
    partial void OnvchWCChanging(string value);
    partial void OnvchWCChanged();
    partial void OnvchWDChanging(string value);
    partial void OnvchWDChanged();
    partial void OnvchCapacityChanging(string value);
    partial void OnvchCapacityChanged();
    partial void OntxtNote1Changing(string value);
    partial void OntxtNote1Changed();
    partial void OntxtNote2Changing(string value);
    partial void OntxtNote2Changed();
    partial void OntxtNote3Changing(string value);
    partial void OntxtNote3Changed();
    partial void OntxtNote4Changing(string value);
    partial void OntxtNote4Changed();
    partial void OnvchDrillingChanging(string value);
    partial void OnvchDrillingChanged();
    partial void OnvchUPCListChanging(string value);
    partial void OnvchUPCListChanged();
    partial void OnvchExposedChanging(string value);
    partial void OnvchExposedChanged();
    partial void OnvchShortDescChanging(string value);
    partial void OnvchShortDescChanged();
    partial void OniVehicleIDChanging(System.Nullable<int> value);
    partial void OniVehicleIDChanged();
    partial void OniProductClassIDChanging(System.Nullable<int> value);
    partial void OniProductClassIDChanged();
    partial void OndtDateModChanging(System.Nullable<System.DateTime> value);
    partial void OndtDateModChanged();
    partial void OntxtBullet1Changing(string value);
    partial void OntxtBullet1Changed();
    partial void OntxtBullet2Changing(string value);
    partial void OntxtBullet2Changed();
    partial void OntxtBullet3Changing(string value);
    partial void OntxtBullet3Changed();
    partial void OntxtBullet4Changing(string value);
    partial void OntxtBullet4Changed();
    partial void OntxtBullet5Changing(string value);
    partial void OntxtBullet5Changed();
    partial void OnvchLongDescChanging(string value);
    partial void OnvchLongDescChanged();
    partial void OniUniqueIdentifierChanging(System.Nullable<int> value);
    partial void OniUniqueIdentifierChanged();
    partial void OndtDateLastTouchedChanging(System.Nullable<System.DateTime> value);
    partial void OndtDateLastTouchedChanged();
    partial void OntxtNote6Changing(string value);
    partial void OntxtNote6Changed();
    partial void OnInstallTimeChanging(System.Nullable<int> value);
    partial void OnInstallTimeChanged();
    partial void OnSGIDChanging(string value);
    partial void OnSGIDChanged();
    partial void OnCURTIDChanging(string value);
    partial void OnCURTIDChanged();
    partial void OnSGRetailChanging(System.Nullable<decimal> value);
    partial void OnSGRetailChanged();
    partial void OnSGMemPriceChanging(System.Nullable<decimal> value);
    partial void OnSGMemPriceChanged();
    partial void OnInstallSheetChanging(string value);
    partial void OnInstallSheetChanged();
    partial void OnmHitchJobberChanging(System.Nullable<decimal> value);
    partial void OnmHitchJobberChanged();
    #endregion
		
		public Product()
		{
			this._Vehicle = default(EntityRef<Vehicle>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iProductID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iProductID
		{
			get
			{
				return this._iProductID;
			}
			set
			{
				if ((this._iProductID != value))
				{
					this.OniProductIDChanging(value);
					this.SendPropertyChanging();
					this._iProductID = value;
					this.SendPropertyChanged("iProductID");
					this.OniProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductCode", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string vchProductCode
		{
			get
			{
				return this._vchProductCode;
			}
			set
			{
				if ((this._vchProductCode != value))
				{
					this.OnvchProductCodeChanging(value);
					this.SendPropertyChanging();
					this._vchProductCode = value;
					this.SendPropertyChanged("vchProductCode");
					this.OnvchProductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchPriceCode", DbType="NVarChar(100)")]
		public string vchPriceCode
		{
			get
			{
				return this._vchPriceCode;
			}
			set
			{
				if ((this._vchPriceCode != value))
				{
					this.OnvchPriceCodeChanging(value);
					this.SendPropertyChanging();
					this._vchPriceCode = value;
					this.SendPropertyChanged("vchPriceCode");
					this.OnvchPriceCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchHitchUPC", DbType="NVarChar(50)")]
		public string vchHitchUPC
		{
			get
			{
				return this._vchHitchUPC;
			}
			set
			{
				if ((this._vchHitchUPC != value))
				{
					this.OnvchHitchUPCChanging(value);
					this.SendPropertyChanging();
					this._vchHitchUPC = value;
					this.SendPropertyChanged("vchHitchUPC");
					this.OnvchHitchUPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mHitchList", DbType="Money")]
		public System.Nullable<decimal> mHitchList
		{
			get
			{
				return this._mHitchList;
			}
			set
			{
				if ((this._mHitchList != value))
				{
					this.OnmHitchListChanging(value);
					this.SendPropertyChanging();
					this._mHitchList = value;
					this.SendPropertyChanged("mHitchList");
					this.OnmHitchListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mHitchMap", DbType="Money")]
		public System.Nullable<decimal> mHitchMap
		{
			get
			{
				return this._mHitchMap;
			}
			set
			{
				if ((this._mHitchMap != value))
				{
					this.OnmHitchMapChanging(value);
					this.SendPropertyChanging();
					this._mHitchMap = value;
					this.SendPropertyChanged("mHitchMap");
					this.OnmHitchMapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fShippingWeight", DbType="Float")]
		public System.Nullable<double> fShippingWeight
		{
			get
			{
				return this._fShippingWeight;
			}
			set
			{
				if ((this._fShippingWeight != value))
				{
					this.OnfShippingWeightChanging(value);
					this.SendPropertyChanging();
					this._fShippingWeight = value;
					this.SendPropertyChanged("fShippingWeight");
					this.OnfShippingWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchWC", DbType="NVarChar(50)")]
		public string vchWC
		{
			get
			{
				return this._vchWC;
			}
			set
			{
				if ((this._vchWC != value))
				{
					this.OnvchWCChanging(value);
					this.SendPropertyChanging();
					this._vchWC = value;
					this.SendPropertyChanged("vchWC");
					this.OnvchWCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchWD", DbType="NVarChar(50)")]
		public string vchWD
		{
			get
			{
				return this._vchWD;
			}
			set
			{
				if ((this._vchWD != value))
				{
					this.OnvchWDChanging(value);
					this.SendPropertyChanging();
					this._vchWD = value;
					this.SendPropertyChanged("vchWD");
					this.OnvchWDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCapacity", DbType="NVarChar(100)")]
		public string vchCapacity
		{
			get
			{
				return this._vchCapacity;
			}
			set
			{
				if ((this._vchCapacity != value))
				{
					this.OnvchCapacityChanging(value);
					this.SendPropertyChanging();
					this._vchCapacity = value;
					this.SendPropertyChanged("vchCapacity");
					this.OnvchCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtNote1", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string txtNote1
		{
			get
			{
				return this._txtNote1;
			}
			set
			{
				if ((this._txtNote1 != value))
				{
					this.OntxtNote1Changing(value);
					this.SendPropertyChanging();
					this._txtNote1 = value;
					this.SendPropertyChanged("txtNote1");
					this.OntxtNote1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtNote2", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string txtNote2
		{
			get
			{
				return this._txtNote2;
			}
			set
			{
				if ((this._txtNote2 != value))
				{
					this.OntxtNote2Changing(value);
					this.SendPropertyChanging();
					this._txtNote2 = value;
					this.SendPropertyChanged("txtNote2");
					this.OntxtNote2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtNote3", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string txtNote3
		{
			get
			{
				return this._txtNote3;
			}
			set
			{
				if ((this._txtNote3 != value))
				{
					this.OntxtNote3Changing(value);
					this.SendPropertyChanging();
					this._txtNote3 = value;
					this.SendPropertyChanged("txtNote3");
					this.OntxtNote3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtNote4", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string txtNote4
		{
			get
			{
				return this._txtNote4;
			}
			set
			{
				if ((this._txtNote4 != value))
				{
					this.OntxtNote4Changing(value);
					this.SendPropertyChanging();
					this._txtNote4 = value;
					this.SendPropertyChanged("txtNote4");
					this.OntxtNote4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDrilling", DbType="NVarChar(25)")]
		public string vchDrilling
		{
			get
			{
				return this._vchDrilling;
			}
			set
			{
				if ((this._vchDrilling != value))
				{
					this.OnvchDrillingChanging(value);
					this.SendPropertyChanging();
					this._vchDrilling = value;
					this.SendPropertyChanged("vchDrilling");
					this.OnvchDrillingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchUPCList", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string vchUPCList
		{
			get
			{
				return this._vchUPCList;
			}
			set
			{
				if ((this._vchUPCList != value))
				{
					this.OnvchUPCListChanging(value);
					this.SendPropertyChanging();
					this._vchUPCList = value;
					this.SendPropertyChanged("vchUPCList");
					this.OnvchUPCListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchExposed", DbType="NVarChar(50)")]
		public string vchExposed
		{
			get
			{
				return this._vchExposed;
			}
			set
			{
				if ((this._vchExposed != value))
				{
					this.OnvchExposedChanging(value);
					this.SendPropertyChanging();
					this._vchExposed = value;
					this.SendPropertyChanged("vchExposed");
					this.OnvchExposedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchShortDesc", DbType="NVarChar(500)")]
		public string vchShortDesc
		{
			get
			{
				return this._vchShortDesc;
			}
			set
			{
				if ((this._vchShortDesc != value))
				{
					this.OnvchShortDescChanging(value);
					this.SendPropertyChanging();
					this._vchShortDesc = value;
					this.SendPropertyChanged("vchShortDesc");
					this.OnvchShortDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iVehicleID", DbType="Int")]
		public System.Nullable<int> iVehicleID
		{
			get
			{
				return this._iVehicleID;
			}
			set
			{
				if ((this._iVehicleID != value))
				{
					if (this._Vehicle.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniVehicleIDChanging(value);
					this.SendPropertyChanging();
					this._iVehicleID = value;
					this.SendPropertyChanged("iVehicleID");
					this.OniVehicleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iProductClassID", DbType="Int")]
		public System.Nullable<int> iProductClassID
		{
			get
			{
				return this._iProductClassID;
			}
			set
			{
				if ((this._iProductClassID != value))
				{
					this.OniProductClassIDChanging(value);
					this.SendPropertyChanging();
					this._iProductClassID = value;
					this.SendPropertyChanged("iProductClassID");
					this.OniProductClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtDateMod", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtDateMod
		{
			get
			{
				return this._dtDateMod;
			}
			set
			{
				if ((this._dtDateMod != value))
				{
					this.OndtDateModChanging(value);
					this.SendPropertyChanging();
					this._dtDateMod = value;
					this.SendPropertyChanged("dtDateMod");
					this.OndtDateModChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtBullet1", DbType="NVarChar(150)")]
		public string txtBullet1
		{
			get
			{
				return this._txtBullet1;
			}
			set
			{
				if ((this._txtBullet1 != value))
				{
					this.OntxtBullet1Changing(value);
					this.SendPropertyChanging();
					this._txtBullet1 = value;
					this.SendPropertyChanged("txtBullet1");
					this.OntxtBullet1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtBullet2", DbType="NVarChar(150)")]
		public string txtBullet2
		{
			get
			{
				return this._txtBullet2;
			}
			set
			{
				if ((this._txtBullet2 != value))
				{
					this.OntxtBullet2Changing(value);
					this.SendPropertyChanging();
					this._txtBullet2 = value;
					this.SendPropertyChanged("txtBullet2");
					this.OntxtBullet2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtBullet3", DbType="NVarChar(150)")]
		public string txtBullet3
		{
			get
			{
				return this._txtBullet3;
			}
			set
			{
				if ((this._txtBullet3 != value))
				{
					this.OntxtBullet3Changing(value);
					this.SendPropertyChanging();
					this._txtBullet3 = value;
					this.SendPropertyChanged("txtBullet3");
					this.OntxtBullet3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtBullet4", DbType="NVarChar(150)")]
		public string txtBullet4
		{
			get
			{
				return this._txtBullet4;
			}
			set
			{
				if ((this._txtBullet4 != value))
				{
					this.OntxtBullet4Changing(value);
					this.SendPropertyChanging();
					this._txtBullet4 = value;
					this.SendPropertyChanged("txtBullet4");
					this.OntxtBullet4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtBullet5", DbType="NVarChar(150)")]
		public string txtBullet5
		{
			get
			{
				return this._txtBullet5;
			}
			set
			{
				if ((this._txtBullet5 != value))
				{
					this.OntxtBullet5Changing(value);
					this.SendPropertyChanging();
					this._txtBullet5 = value;
					this.SendPropertyChanged("txtBullet5");
					this.OntxtBullet5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchLongDesc", DbType="NVarChar(1500)")]
		public string vchLongDesc
		{
			get
			{
				return this._vchLongDesc;
			}
			set
			{
				if ((this._vchLongDesc != value))
				{
					this.OnvchLongDescChanging(value);
					this.SendPropertyChanging();
					this._vchLongDesc = value;
					this.SendPropertyChanged("vchLongDesc");
					this.OnvchLongDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iUniqueIdentifier", DbType="Int")]
		public System.Nullable<int> iUniqueIdentifier
		{
			get
			{
				return this._iUniqueIdentifier;
			}
			set
			{
				if ((this._iUniqueIdentifier != value))
				{
					this.OniUniqueIdentifierChanging(value);
					this.SendPropertyChanging();
					this._iUniqueIdentifier = value;
					this.SendPropertyChanged("iUniqueIdentifier");
					this.OniUniqueIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtDateLastTouched", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtDateLastTouched
		{
			get
			{
				return this._dtDateLastTouched;
			}
			set
			{
				if ((this._dtDateLastTouched != value))
				{
					this.OndtDateLastTouchedChanging(value);
					this.SendPropertyChanging();
					this._dtDateLastTouched = value;
					this.SendPropertyChanged("dtDateLastTouched");
					this.OndtDateLastTouchedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtNote6", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string txtNote6
		{
			get
			{
				return this._txtNote6;
			}
			set
			{
				if ((this._txtNote6 != value))
				{
					this.OntxtNote6Changing(value);
					this.SendPropertyChanging();
					this._txtNote6 = value;
					this.SendPropertyChanged("txtNote6");
					this.OntxtNote6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstallTime", DbType="Int")]
		public System.Nullable<int> InstallTime
		{
			get
			{
				return this._InstallTime;
			}
			set
			{
				if ((this._InstallTime != value))
				{
					this.OnInstallTimeChanging(value);
					this.SendPropertyChanging();
					this._InstallTime = value;
					this.SendPropertyChanged("InstallTime");
					this.OnInstallTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGID", DbType="NChar(16)")]
		public string SGID
		{
			get
			{
				return this._SGID;
			}
			set
			{
				if ((this._SGID != value))
				{
					this.OnSGIDChanging(value);
					this.SendPropertyChanging();
					this._SGID = value;
					this.SendPropertyChanged("SGID");
					this.OnSGIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURTID", DbType="NChar(16)")]
		public string CURTID
		{
			get
			{
				return this._CURTID;
			}
			set
			{
				if ((this._CURTID != value))
				{
					this.OnCURTIDChanging(value);
					this.SendPropertyChanging();
					this._CURTID = value;
					this.SendPropertyChanged("CURTID");
					this.OnCURTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGRetail", DbType="Money")]
		public System.Nullable<decimal> SGRetail
		{
			get
			{
				return this._SGRetail;
			}
			set
			{
				if ((this._SGRetail != value))
				{
					this.OnSGRetailChanging(value);
					this.SendPropertyChanging();
					this._SGRetail = value;
					this.SendPropertyChanged("SGRetail");
					this.OnSGRetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGMemPrice", DbType="Money")]
		public System.Nullable<decimal> SGMemPrice
		{
			get
			{
				return this._SGMemPrice;
			}
			set
			{
				if ((this._SGMemPrice != value))
				{
					this.OnSGMemPriceChanging(value);
					this.SendPropertyChanging();
					this._SGMemPrice = value;
					this.SendPropertyChanged("SGMemPrice");
					this.OnSGMemPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstallSheet", DbType="NVarChar(50)")]
		public string InstallSheet
		{
			get
			{
				return this._InstallSheet;
			}
			set
			{
				if ((this._InstallSheet != value))
				{
					this.OnInstallSheetChanging(value);
					this.SendPropertyChanging();
					this._InstallSheet = value;
					this.SendPropertyChanged("InstallSheet");
					this.OnInstallSheetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mHitchJobber", DbType="Money")]
		public System.Nullable<decimal> mHitchJobber
		{
			get
			{
				return this._mHitchJobber;
			}
			set
			{
				if ((this._mHitchJobber != value))
				{
					this.OnmHitchJobberChanging(value);
					this.SendPropertyChanging();
					this._mHitchJobber = value;
					this.SendPropertyChanged("mHitchJobber");
					this.OnmHitchJobberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vehicle_Product", Storage="_Vehicle", ThisKey="iVehicleID", OtherKey="iVehicleID", IsForeignKey=true)]
		public Vehicle Vehicle
		{
			get
			{
				return this._Vehicle.Entity;
			}
			set
			{
				Vehicle previousValue = this._Vehicle.Entity;
				if (((previousValue != value) 
							|| (this._Vehicle.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vehicle.Entity = null;
						previousValue.Products.Remove(this);
					}
					this._Vehicle.Entity = value;
					if ((value != null))
					{
						value.Products.Add(this);
						this._iVehicleID = value.iVehicleID;
					}
					else
					{
						this._iVehicleID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Vehicle");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
